---
- name: http-server
  hosts: ya[0]
  become: true
  roles:
    - role: http
      tags: http
    - role: users
      tags: users  

- name: php-server
  hosts: ya[1]
  become: true
  roles:
    - role: php
      tags: php
    - role: users
      tags: users
